config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  root to: 'home#landing_page'
  get '/get_products', to: 'home#get_products'
  resources :products, only: %i[index new create edit update]
  resources :orders, only: %i[index new create]
  resources :forecastings, only: %i[index show]
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :product_orders, dependent: :destroy
  has_many :products, through: :product_orders

  accepts_nested_attributes_for :product_orders

  scope :newest, -> { order('created_at DESC') }
  scope :oldest, -> { order('created_at ASC') }

  validates :order_number, :price, presence: true
  validate :products_count

  before_validation :count_price

  private

  def count_price
    if price.blank?
      self.price = product_orders.sum { |po| po.quantity * po.product.price }
    end
  rescue NoMethodError
    errors.add(:product_orders, "Nie wypełniłeś wszystkich pól")
  end

  def products_count
    product_orders.each do |product_order|
      product = product_order.product.name
      if product_order.quantity.nil? || Integer(product_order.quantity) < 0
        errors.add("product_order_#{product}", "Wartość musi być liczbą wiekszą od 0")
        next
      end
      if product_order.quantity > product_order.product.availability
        errors.add("product_order_#{product}", "Niewystarczająca ilość produktu na magazynie")
      end
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all.newest
  end

  def new
    @order = Order.new
    @order.product_orders.build
    @products = Product.alphabetically
  end

  def create
    @order              = Order.new(order_params)
    @order.order_number = "#{DateTime.now.strftime('%Y/%m/%d/%H%M%S%L')}"
    if @order.save
      @order.product_orders.each do |po|
        po.product.update!(availability: po.product.availability - po.quantity)
      end
      successfully_response(object: { message: 'Pomyślnie złożono zamówienie' },
                            notice: 'Pomyślnie złożono zamówienie',
                            path:   orders_path)
    else
      @products = Product.alphabetically
      @order.product_orders.build if @order.product_orders.blank?
      not_valid_response(object: @order, action: 'new')
    end
  end

  private

  def order_params
    params.require(:order).permit(product_orders_attributes: [:product_id, :quantity])
  end
end

app/views/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col flex-right">
      <%= link_to 'Dodaj nowy', new_order_path, class: 'btn btn-secondary button-margin-vertical' %>
    </div>
  </div>
</div>
<div class="container flex-column-center">
  <table class="table table-dark table-striped">
    <thead>
    <tr class="table-dark">
      <th class="table-dark" scope="col">Numer zamówienia</th>
      <th class="table-dark" scope="col">Cena</th>
      <th class="table-dark" scope="col">Data zamówienia</th>
    </tr>
    </thead>
    <tbody>
    <% @orders.each do |order| %>
      <tr class="table-dark">
        <th scope="row"><%= order.order_number %></th>
        <td class="table-dark"><%= number_to_currency(order.price, unit: :zł, format: "%n %u") %></td>
        <td class="table-dark"><%= year_month_date(order.created_at) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/orders/new.html.erb
<div class="container" data-controller="order-form">
  <%= simple_form_for @order do |f| %>
    <div class="container">
      <div class="row flex-center">
        <div class="col-10 flex-left button-margin-vertical">
          <%= link_to 'Wróć do listy zamówień', orders_path, class: 'btn btn-link button-margin-vertical' %>
        </div>
      </div>
      <div class="row flex-center">
        <div class="col-6 flex-column-center input form-container">
          <div class="mb-4">
            <h4>Składanie nowego zamówienia</h4>
          </div>
          <%= f.error :product_orders, class: 'border border-2 border-danger text-danger margin-normal small-padding' %>
          <% @order.product_orders&.each_with_index do |product_order, i| %>
            <%= f.simple_fields_for :product_orders, product_order do |po| %>
              <div id="<%= "po_#{i}" %>" class="mb-4 flex-column full-width">
                <div class="mb-4 flex-left full-width">
                  <div class="small-margin-lr">
                    <label for="exampleFormControlInput1" class="form-label">Wybierz produkt</label>
                    <%= po.input :product_id, as: :select, selected: product_order.product_id || '', collection: @products, input_html: { class: 'dark-input' }, label: false %>
                  </div>
                  <div>
                    <label for="exampleFormControlInput1" class="form-label">Podaj ilość</label>
                    <%= po.input :quantity, as: :integer, input_html: { class: 'dark-input' }, label: false %>
                  </div>
                  <% if i > 0 %>
                    <div class="small-margin-lr">
                      <div class="btn btn-secondary" data-action="click->order-form#removeAssociations" value="<%= i %>">
                        -
                      </div>
                      <%= po.input :_destroy, id: "destroy_#{i}", as: :hidden %>
                    </div>
                  <% end %>
                </div>
                <% if @order.try(:errors).try(:messages).present? %>
                  <div class="text-danger">
                    <% @order.errors.messages[:"product_order_#{product_order.product.name}"].each do |error| %>
                      <div class="flex-center error mb-4">
                        <%= error %>
                      </div>
                    <% end %>
                  </div>
                <% end %>
              </div>
            <% end %>
          <% end %>
          <templete data-order-form-target="template" class="hidden">
            <%= f.simple_fields_for :product_orders, ProductOrder.new, child_index: 'TEMPLATE_FIELD' do |po| %>
              <div id="po_TEMPLATE_FIELD" class="mb-4 flex-column full-width">
                <div class="mb-4 flex-left full-width">
                  <div class="small-margin-lr">
                    <%= po.input :product_id, as: :select, collection: @products, input_html: { class: 'dark-input' }, label: false %>
                  </div>
                  <div>
                    <%= po.input :quantity, as: :integer, input_html: { class: 'dark-input' }, label: false %>
                  </div>
                  <div class="small-margin-lr">
                    <div class="btn btn-secondary" data-action="click->order-form#removeAssociations" value="TEMPLATE_FIELD">
                      -
                    </div>
                    <%= po.input :_destroy, id: "destroy_TEMPLATE_FIELD", as: :hidden %>
                  </div>
                </div>
              </div>
            <% end %>
          </templete>
          <div>
            <div class="btn btn-light button-margin-vertical" data-action="click->order-form#addAssociation">
              Dodaj produkt
            </div>
          </div>
          <div class="mb-4">
            <%= f.submit 'Zamów', class: 'btn btn-secondary button-margin-vertical' %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>